project_id = "mlocikcfxbleddsvxciv"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.process-ai-message]
verify_jwt = false

[functions.clone-page]
verify_jwt = false

[functions.agent-customer-auth]
verify_jwt = false

[functions.chatbot-customer-auth]
verify_jwt = false

[functions.process-agent-customer-message]
verify_jwt = false

[functions.init-agent-conversation]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.chatbot-customer-message]
verify_jwt = false

[functions.create-mercadopago-preference]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false