INSERT INTO public.site_settings (key, value, description)
VALUES (
  'faqs',
  $json$[
    {"id":"f1","order_index":0,"question":"O que é a Out App?","answer":"A Out App é uma plataforma tudo em um que reúne ferramentas inteligentes para criar, organizar, automatizar e gerenciar seu negócio. Em um só lugar você tem chat online, gestão livre de cadastros, gestão financeira, criador de catálogo, portfólio, página de captura, área de membros, checkout, contratos, briefings, questionário de marketing e muito mais."},
    {"id":"f2","order_index":1,"question":"Quanto custa a Out App?","answer":"O plano mensal custa R$ 49,90 por mês. O plano anual custa R$ 358,80 à vista, o que sai a R$ 29,90 o mês — uma economia de 40% em relação ao mensal."},
    {"id":"f3","order_index":2,"question":"Qual a diferença entre o plano mensal e o anual?","answer":"Os dois planos liberam todos os recursos da plataforma, sem limite de funcionalidades. A diferença está no preço: no mensal você paga R$ 49,90 por mês, e no anual paga R$ 358,80 uma única vez, o que equivale a R$ 29,90 por mês durante 12 meses."},
    {"id":"f4","order_index":3,"question":"Existe teste grátis?","answer":"Sim. Você tem 3 dias de teste gratuito para experimentar a plataforma, sem precisar cadastrar cartão de crédito. Depois é só escolher o plano mensal ou anual para continuar com acesso completo."},
    {"id":"f5","order_index":4,"question":"Como funciona o Chat Online?","answer":"Você cria um chat com link próprio e o cliente entra apenas informando nome e e-mail, sem precisar criar conta. Você controla o status do atendente (online, ocupado ou offline), monta uma fila de espera com posição e tempo estimado, recebe notificações em tempo real e ainda oferece um formulário de contato por e-mail quando não há atendente disponível."},
    {"id":"f6","order_index":5,"question":"O que é a Gestão Livre?","answer":"É o módulo de cadastros da Out App. Você cria categorias e subcategorias do seu jeito (clientes, fornecedores, produtos, serviços e o que mais precisar), define campos personalizados, controla status, evita números duplicados e organiza a lista arrastando os registros na ordem que quiser."},
    {"id":"f7","order_index":6,"question":"Posso atribuir recursos a um cadastro?","answer":"Sim. Qualquer recurso criado na plataforma — contrato, briefing, catálogo, portfólio, checkout, área de membros, chat e outros — pode ser vinculado a um cadastro. Na aba Atribuições você vê tudo que pertence àquele contato e acessa cada item com um clique."},
    {"id":"f8","order_index":7,"question":"Como funciona o Criador de Catálogo?","answer":"Você monta uma loja completa com layout totalmente editável (cabeçalho, banners, categorias, benefícios e rodapé), usa as subcategorias da Gestão Livre como seções, cria páginas institucionais e recebe pagamentos por PIX manual com QR Code ou pelo Mercado Pago. No painel você acompanha pedidos, status de pagamento, relatórios e analytics."},
    {"id":"f9","order_index":8,"question":"Consigo receber pagamentos pela plataforma?","answer":"Sim. O Criador de Checkout e o Criador de Catálogo têm integração com o Mercado Pago e também opção de PIX manual com QR Code. Você acompanha todos os pedidos, confirmações de pagamento e relatórios direto no painel."},
    {"id":"f10","order_index":9,"question":"O que dá para fazer com a Área de Membros?","answer":"Você publica cursos e conteúdos exclusivos com banners na tela inicial, capa personalizada em cada módulo, liberação por código de acesso e área de perguntas e respostas por vídeo, onde cada aluno pergunta e você responde."},
    {"id":"f11","order_index":10,"question":"Quais ferramentas de captação de leads estão inclusas?","answer":"Você conta com Criador de Página de Captura, Criador de Portfólio, Questionário Marketing, formulários do chat online, pop-ups, botões flutuantes e encurtador de links. Todos os leads capturados ficam organizados nos cadastros da plataforma."},
    {"id":"f12","order_index":11,"question":"A gestão financeira serve para o meu negócio?","answer":"Sim. Você registra receitas e despesas, organiza por categorias, informa em qual banco o dinheiro entrou ou saiu, acompanha o status de cada transação, ordena tudo arrastando e ainda pode criar uma gestão financeira separada para cada cadastro."},
    {"id":"f13","order_index":12,"question":"Posso cancelar quando quiser?","answer":"Sim. Não há fidelidade. Você pode cancelar a renovação a qualquer momento e continuar usando a plataforma normalmente até o fim do período já pago."},
    {"id":"f14","order_index":13,"question":"Preciso instalar alguma coisa?","answer":"Não. A Out App funciona direto no navegador, em computador, tablet ou celular. Também é possível instalar como aplicativo na tela inicial do seu dispositivo."}
  ]$json$,
  'FAQs da landing page'
)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;