
-- Add integration fields to checkouts
ALTER TABLE public.checkouts
ADD COLUMN integration_type TEXT DEFAULT NULL, -- 'catalog', 'members_area', or null
ADD COLUMN integration_id UUID DEFAULT NULL; -- references catalog_id or members_area_id

-- Table for members area access codes generated by checkout purchases
CREATE TABLE public.members_area_access_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  members_area_id UUID NOT NULL REFERENCES public.simple_members_areas(id) ON DELETE CASCADE,
  checkout_order_id UUID REFERENCES public.checkout_orders(id) ON DELETE SET NULL,
  user_id UUID NOT NULL,
  access_code TEXT NOT NULL UNIQUE,
  customer_name TEXT,
  customer_email TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ DEFAULT NULL
);

ALTER TABLE public.members_area_access_codes ENABLE ROW LEVEL SECURITY;

-- Owner can manage access codes via their members areas
CREATE POLICY "Owner can manage access codes"
ON public.members_area_access_codes
FOR ALL USING (auth.uid() = user_id);

-- Public can read to verify codes (for login)
CREATE POLICY "Anyone can verify access codes"
ON public.members_area_access_codes
FOR SELECT USING (true);

-- Function to generate unique access code
CREATE OR REPLACE FUNCTION public.generate_checkout_access_code()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  code TEXT;
  done BOOL;
BEGIN
  done := false;
  WHILE NOT done LOOP
    code := upper(substring(md5(random()::text || clock_timestamp()::text) from 1 for 8));
    done := NOT EXISTS(SELECT 1 FROM public.members_area_access_codes WHERE access_code = code);
  END LOOP;
  RETURN code;
END;
$$;
