// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlocikcfxbleddsvxciv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sb2Npa2NmeGJsZWRkc3Z4Y2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMjcxOTYsImV4cCI6MjA3NTcwMzE5Nn0.BN-spC1ijxlrQahDRaRDcx2Y50Q_0H5eY0UpIaNLDyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});